CELERY_IMPORTS = ("twttr")

CELERY_RESULT_BACKEND = "database"
CELERY_RESULT_DBURI = "sqlite:///data.sqlite"
CELERY_SEND_EVENTS = True
CELERY_SEND_TASK_SENT_EVENT = True

BROKER_HOST = "localhost"
BROKER_PORT = 5672
BROKER_VHOST = "lottery"
BROKER_USER = "lottery-worker"
BROKER_PASSWORD = "LOTS"

CELERYD_CONCURRENCY = 6
